# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 20:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issueLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='issued_by',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
